### ISSUE TITLE
Request for the training logs of PiT on ImageNet

### ISSUE THREAD

**Issue by HeegonJin** [naver-ai/pit#4]
Hello, Can you release the training logs of pit on imagenet?
It would be very great if you share it.

**Comment by bhheo** [comment]
Hi

I'm sorry but, I lost some of the training logs of pit due to server issues.
I checked the servers and here is the list of remaining logs.

`log_PiT-B_distill_84_0.txt`
`log_PiT-S_distill_81_9.txt`
`log_PiT-Ti_distill_74_6.txt`
`log_PiT-S_80_9.txt`

If you still want these logs please email me.

There is a risk that log files include information on the company's servers, which is prohibited on company policy.
I double-checked but, I still want to use email rather than public release.
